search:
  client:
    naver:
      id: x6tmsVBuLuVZnCtS0iI0
      key: tFjClHjwzs
    kakao:
      key: KakaoAK 4013eda58e386eb56c1a9f9ebf68d488
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:app
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true


resilience4j:
  circuitbreaker:
    failure-rate-threshold: 10   # 실패 10% 이상 시 서킷 오픈
    slow-call-duration-threshold: 500   # 500ms 이상 소요 시 실패로 간주
    slow-call-rate-threshold: 10   # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
    wait-duration-in-open-state: 30000   # OPEN -> HALF-OPEN 전환 전 기다리는 시간
    minimum-number-of-calls: 1   # 집계에 필요한 최소 호출 수
    sliding-window-size: 1   # 서킷 CLOSE 상태에서 N회 호출 도달 시 failureRateThreshold 실패 비율 계산
    permitted-number-of-calls-in-half-open-state: 30   # HALFOPEN -> CLOSE or OPEN 으로 판단하기 위해 호출 횟수
  retry:
    wait-duration: 100   # 재시도 사이 간격
    max-attempts: 2   # 재시도 횟수(최초 호출 포함)