search:
  client:
    naver:
      id: x6tmsVBuLuVZnCtS0iI0
      key: tFjClHjwzs
    kakao:
      key: KakaoAK 4013eda58e386eb56c1a9f9ebf68d488
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:app
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

resilience4j:
  circuitbreaker:
    instances:
      search:
        slidingWindowSize: 1
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 30
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 20
        registerHealthIndicator: false